"""empty message

Revision ID: a3ccbfd1e2c7
Revises: bf41a372450c
Create Date: 2025-02-01 03:44:05.809435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ccbfd1e2c7'
down_revision = 'bf41a372450c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eyecolor', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('age', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('eyecolor')

    # ### end Alembic commands ###
